### ISSUE TITLE
[Question] Why is Switzerland "a bad country"?

### ISSUE THREAD

**Issue by m1karii** [MiMillieuh/MiMillieuh.github.io#1]

**Comment by MiMillieuh** [comment]
Because.

**Comment by m1karii** [comment]
wdym because?

i was thinking of moving there some time in the future - that's why i'm asking

**Comment by MiMillieuh** [comment]
> wdym because?
> 
> i was thinking of moving there some time in the future - that's why i'm asking

Then don't do your nationality before you're 35. trust me. and I won't tell anything more about that or I'll just depress myself more than I'm already.
